[package]
name = "bedfellow-api"
version = "0.1.0"
authors = ["Dublin Anondson <stratophone2112@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

