name: bedfellow-test-runner
on: [pull_request]
jobs:
  run-lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test
    env:
      SPOTIFY_CLIENT_ID: client_id
      SPOTIFY_AUTHORIZE_URL: http://localhost/authorize
      SPOTIFY_REDIRECT_URI_ANDROID: com.bedfellow://callback/
      SPOTIFY_REDIRECT_URI: org.danondso.bedfellow://callback/
      SPOTIFY_TOKEN_REFRESH_URL: http://localhost/refresh
      SPOTIFY_TOKEN_URL: http://localhost/token
      WHOSAMPLED_BASE_URL: https://www.whosampled.com
      
