name: bedfellow-test-runner
on: [pull_request]
jobs:
  run-lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test