name: bedfellow-test-runner
on: [pull_request]
jobs:
  run-lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '20'
      - run: yarn install
      - run: yarn lint
      - run: yarn test
    env:
      SPOTIFY_CLIENT_ID: client_id
      SPOTIFY_REDIRECT_URI_ANDROID: com.bedfellow://callback/
      SPOTIFY_REDIRECT_URI: org.danondso.bedfellow://callback/
      WHOSAMPLED_BASE_URL: https://www.whosampled.com
